### ISSUE TITLE
本番環境にデプロイする

### ISSUE THREAD

**Issue by tegnike** [tegnike/aituber-kit#100]
## 議題

本番環境にデプロイする
どのサービスが一番カンタンかを検証、Vercelが良い？

### TTS

- Google TTSが一番安い
- Koeiromapは2円/req、流石に高い

### LLM

- 少額クレジット用意してHaiku？
- 無料のAIサービス使えるかも確認

**Comment by FoundD-oka** [comment]
VercelにデプロイしたらTypeScriptの型エラーが出ました。
messageプロパティがstring型であるべきところに、配列[{ type: string; text: string; }, { type: string; image_url: { url: string; }; }]が渡されているためらしいです・・・。涙

**Comment by tegnike** [comment]
@FoundD-oka 

あ、ちゃんとlint通してエラーチェックできてないですね…  
確認します〜

**Comment by tegnike** [comment]
@FoundD-oka 
修正しました！私の環境ではvercelでデプロイできたのですが、いかがでしょうか？

**Comment by FoundD-oka** [comment]
いけましたー！
私の環境からもvercelでスルッとデプロイできました。
対応ありがとうございます！！
