### ISSUE TITLE
UE5.4 で Meta Human と連動してほしい。

### ISSUE THREAD

**Issue by screny** [tegnike/aituber-kit#26]
UE5.4 で Meta Human とAPI接続で連動してほしい。
＼(^o^)／つばさぁ！

**Comment by tegnike** [comment]
これよく理解できてないのですが、具体的に説明いただくことできますか？
何を実現したくて、その機能があるとどう嬉しいのかが知りたいです。

**Comment by screny** [comment]
https://create.fortnite.com/news/metahuman-now-available-for-uefn-bring-digital-human-npcs-to-your-islands?lang=ja&team=personal
![image](https://github.com/tegnike/nike-ChatVRM/assets/5644598/4ab9d69f-7ed8-44e1-92a0-7e6ab3caaef8)

**Comment by screny** [comment]
![image](https://github.com/tegnike/nike-ChatVRM/assets/5644598/74fcd650-3906-425b-9130-2f3849bec420)
https://metahumansdk.io/

**Comment by tegnike** [comment]
このブラウザアプリ上にMetaHumanを導入したいということでしょうか？
今はVRMという3Dモデルを使用していますが、このMetaHumanというのはブラウザ上で動かすためのSDKが公開されていますか？
